#include "readfunc.h"
#include "errorhandler.h"
#include "growthimplement.h"
#include "readword.h"
#include "gadget.h"

GrowthImplementparameters::GrowthImplementparameters(CommentStream& infile) {
  ErrorHandler handle;
  char text[MaxStrLength];
  strncpy(text, "", MaxStrLength);
  int i, j;

  //Read two first lines which are not used
  infile >> text >> ws >> text >> ws >> text >> ws >> text >> ws;

  ReadWordAndVariable(infile, "minlengthgroupgrowth", minlengthgroupgrowth);
  ReadWordAndVariable(infile, "maxlengthgroupgrowth", maxlengthgroupgrowth);
  ReadWordAndVariable(infile, "meanresolution", meanresolution);
  ReadWordAndVariable(infile, "nmean", nmean);
  ReadWordAndVariable(infile, "varresolution", varresolution);
  ReadWordAndVariable(infile, "nvariance", nvar);

  //The distribution file is generated by the program growthdisp.
  //The first 7 columns are not needed here so the matrix tmpmatrix is needed.
  int nrow = nmean * nvar;
  doublematrix tmpmatrix(nrow, maxlengthgroupgrowth - minlengthgroupgrowth + 1 + 7);
  distribution.AddRows(nrow, maxlengthgroupgrowth - minlengthgroupgrowth + 1);
  realvariance.resize(nrow);

  infile >> text;
  if (strcasecmp(text, "distribution") == 0)
    ReadMatrix(infile, tmpmatrix);
  else
    handle.Unexpected("distribution", text);

  for (i = 0; i < nrow; i++) {
    for (j = 0; j < distribution.Ncol(); j++)
      distribution[i][j] = tmpmatrix[i][j + 7];

    realvariance[i] = tmpmatrix[i][5];
  }
}
