// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gadget
Rcpp::List gadget(Rcpp::StringVector args);
RcppExport SEXP _gadgetr_gadget(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(gadget(args));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gadgetr_gadget", (DL_FUNC) &_gadgetr_gadget, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_gadgetr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
