# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getEcosystemInfo <- function() {
    .Call(`_gadgetr_getEcosystemInfo`)
}

getStockInfoC <- function(stockNo) {
    .Call(`_gadgetr_getStockInfoC`, stockNo)
}

updateRenewalC <- function(stockNo, year, step, area, age, number, mean, sdev, alpha, beta, length, meanWeight) {
    .Call(`_gadgetr_updateRenewalC`, stockNo, year, step, area, age, number, mean, sdev, alpha, beta, length, meanWeight)
}

updateSuitabilityC <- function(fleetNo, stockNo, len, value) {
    .Call(`_gadgetr_updateSuitabilityC`, fleetNo, stockNo, len, value)
}

printPredatorPrey <- function(fleetNo, stockNo) {
    .Call(`_gadgetr_printPredatorPrey`, fleetNo, stockNo)
}

printStock <- function(stockNo) {
    .Call(`_gadgetr_printStock`, stockNo)
}

printSSB <- function(stockNo) {
    .Call(`_gadgetr_printSSB`, stockNo)
}

updateRecruitementC <- function(stockNo, recruitParams) {
    .Call(`_gadgetr_updateRecruitementC`, stockNo, recruitParams)
}

wholeSim <- function() {
    .Call(`_gadgetr_wholeSim`)
}

updateAmountStep <- function(fleetNo, step, area, value) {
    .Call(`_gadgetr_updateAmountStep`, fleetNo, step, area, value)
}

updateAmountYear <- function(fleetNo, year, step, area, value) {
    .Call(`_gadgetr_updateAmountYear`, fleetNo, year, step, area, value)
}

initSim <- function() {
    .Call(`_gadgetr_initSim`)
}

stepSim <- function() {
    .Call(`_gadgetr_stepSim`)
}

yearSim <- function() {
    .Call(`_gadgetr_yearSim`)
}

finalizeSim <- function() {
    .Call(`_gadgetr_finalizeSim`)
}

finalize <- function() {
    .Call(`_gadgetr_finalize`)
}

gadget <- function(args) {
    .Call(`_gadgetr_gadget`, args)
}

isGadgetInitialized <- function() {
    .Call(`_gadgetr_isGadgetInitialized`)
}

