# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getEcosystemInfo <- function() {
    .Call(`_gadgetr_getEcosystemInfo`)
}

updateRecruitment <- function(stockName) {
    .Call(`_gadgetr_updateRecruitment`, stockName)
}

updateSuitability <- function(fleetNo, stockName, len, value) {
    .Call(`_gadgetr_updateSuitability`, fleetNo, stockName, len, value)
}

wholeSim <- function() {
    .Call(`_gadgetr_wholeSim`)
}

updateAmountStep <- function(fleetNo, step, area, value) {
    .Call(`_gadgetr_updateAmountStep`, fleetNo, step, area, value)
}

updateAmountYear <- function(fleetNo, year, step, area, value) {
    .Call(`_gadgetr_updateAmountYear`, fleetNo, year, step, area, value)
}

initSim <- function() {
    .Call(`_gadgetr_initSim`)
}

stepSim <- function() {
    .Call(`_gadgetr_stepSim`)
}

yearSim <- function() {
    .Call(`_gadgetr_yearSim`)
}

finalizeSim <- function() {
    .Call(`_gadgetr_finalizeSim`)
}

finalize <- function() {
    .Call(`_gadgetr_finalize`)
}

gadget <- function(args) {
    .Call(`_gadgetr_gadget`, args)
}

