# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wholeSim <- function() {
    .Call(`_gadgetr_wholeSim`)
}

initSim <- function() {
    .Call(`_gadgetr_initSim`)
}

stepSim <- function() {
    .Call(`_gadgetr_stepSim`)
}

yearSim <- function() {
    .Call(`_gadgetr_yearSim`)
}

finalizeSim <- function() {
    .Call(`_gadgetr_finalizeSim`)
}

finalize <- function() {
    .Call(`_gadgetr_finalize`)
}

gadget <- function(args) {
    .Call(`_gadgetr_gadget`, args)
}

